#!/bin/bash

# Burn After Reading - 自动化生产环境部署脚本
#
# 使用方法:
# 1. 将此脚本上传到您的服务器
# 2. 赋予执行权限: chmod +x deploy_server.sh
# 3. 以root用户身份运行: ./deploy_server.sh your-domain.com
#
# 注意: 此脚本会安装必要的软件，配置Nginx和防火墙，并从GitHub拉取项目代码。

# --- 配置 ---
# 脚本出错时立即退出
set -e

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# --- 函数定义 ---
log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# --- 脚本开始 ---

# 1. 检查参数和权限
if [ "$EUID" -ne 0 ]; then
    log_error "请以root用户身份运行此脚本。"
    exit 1
fi

if [ -z "$1" ]; then
    log_error "缺少域名参数。"
    echo "使用方法: $0 your-domain.com"
    exit 1
fi

DOMAIN=$1
REPO_URL="https://github.com/lgnorant-lu/burn_after_reading.git"
# 统一使用/opt目录作为应用根目录，更规范
APP_DIR="/opt/burn_after_reading"

log_info "🚀 开始部署 Burn After Reading 应用..."
log_info "域名: $DOMAIN"
log_info "部署目录: $APP_DIR"
read -p "确认以上信息并继续? (y/N): " confirm && [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]] || exit 1

# 2. 安装依赖软件
log_info "检查并安装依赖软件 (Git, Docker, Nginx, Certbot)..."
apt-get update
apt-get install -y git curl sudo nginx certbot python3-certbot-nginx

# --- Docker官方版本安装 ---
log_info "正在卸载任何可能存在的旧Docker版本..."
apt-get purge -y docker.io docker-compose containerd runc || true # 使用|| true以忽略未安装时的错误
apt-get autoremove -y --purge

log_info "正在设置Docker官方软件源..."
apt-get install -y ca-certificates
install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
chmod a+r /etc/apt/keyrings/docker.asc

echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
  tee /etc/apt/sources.list.d/docker.list > /dev/null
apt-get update

log_info "正在安装Docker CE (社区版)..."
apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
# --- Docker安装完成 ---

# 3. 拉取或更新项目代码
log_info "从GitHub拉取项目代码..."
if [ -d "$APP_DIR" ]; then
    log_warn "目录 $APP_DIR 已存在。正在拉取最新代码..."
    cd "$APP_DIR"
    git pull
else
    git clone "$REPO_URL" "$APP_DIR"
    cd "$APP_DIR"
fi

# 4. 创建生产环境 .env 文件
log_info "创建生产环境配置文件 .env.prod..."
# 生成一个安全的随机密钥
SECRET_KEY=$(openssl rand -hex 32)
cat > .env.prod << EOF
# Auto-generated by deploy_server.sh
APP_ENV=production
SECRET_KEY=${SECRET_KEY}
SQLALCHEMY_DATABASE_URL="sqlite:///./data/burn_after_reading.db"
CORS_ORIGINS=https://${DOMAIN}
MAX_FILE_SIZE_BYTES=5242880
CLIENT_MAX_BODY_SIZE=5M
EOF
log_info ".env.prod 文件已创建，并生成了新的SECRET_KEY。"

# 5. 配置Nginx (智能路径选择)
log_info "配置 Nginx..."

# 探测Nginx配置目录
if [ -d "/www/server/panel/vhost/nginx" ]; then
    NGINX_CONF_DIR="/www/server/panel/vhost/nginx"
    NGINX_CMD="/www/server/nginx/sbin/nginx"
    # 宝塔环境下，为Certbot创建验证目录
    ACME_DIR="/www/wwwroot/$DOMAIN"
    log_info "检测到宝塔面板环境，使用路径: $NGINX_CONF_DIR"
else
    NGINX_CONF_DIR="/etc/nginx/sites-available"
    NGINX_CMD="nginx"
    ACME_DIR="/var/www/html"
    log_info "使用标准Nginx环境路径: $NGINX_CONF_DIR"
fi
NGINX_CONFIG_FILE="$NGINX_CONF_DIR/$DOMAIN.conf"

# --- 步骤 5.1: 配置HTTP服务以供Certbot验证 ---
log_info "配置HTTP服务用于SSL证书申请..."
cat > "$NGINX_CONFIG_FILE" << EOF
server {
    listen 80;
    server_name $DOMAIN;

    root $ACME_DIR;
    location /.well-known/acme-challenge/ {
        allow all;
    }

    location / {
       return 404; # 在获取证书前，拒绝所有其他请求
    }
}
EOF

# 创建验证目录
mkdir -p "$ACME_DIR"

# 测试并重载Nginx
log_info "测试并重载Nginx配置..."
$NGINX_CMD -t
systemctl reload nginx

# --- 步骤 5.2: 申请SSL证书 ---
log_info "使用Certbot申请SSL证书..."
certbot certonly --webroot -w "$ACME_DIR" -d "$DOMAIN" --register-unsafely-without-email --agree-tos --non-interactive

# --- 步骤 5.3: 配置最终的HTTPS服务 ---
log_info "配置最终的HTTPS服务..."
cat > "$NGINX_CONFIG_FILE" << EOF
server {
    listen 80;
    server_name $DOMAIN;
    # 将所有HTTP请求强制跳转到HTTPS
    return 301 https://\$host\$request_uri;
}

server {
    listen 443 ssl http2;
    server_name $DOMAIN;

    # SSL 证书路径
    ssl_certificate /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;

    # 安全配置
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
    
    # 文件上传大小限制 (应与.env.prod中的CLIENT_MAX_BODY_SIZE匹配)
    client_max_body_size 5M;

    location / {
        proxy_pass http://127.0.0.1:8001; # 直接代理到后端的Docker服务
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
EOF

# 再次测试并重载Nginx
log_info "再次测试并重载Nginx配置以启用HTTPS..."
$NGINX_CMD -t
systemctl reload nginx

# 6. 配置防火墙
log_info "配置防火墙 (UFW)..."
if command -v ufw &> /dev/null; then
    ufw allow 22/tcp  # SSH
    ufw allow 80/tcp  # HTTP
    ufw allow 443/tcp # HTTPS
    ufw --force enable
else
    log_warn "UFW未安装，请手动配置防火墙以开放端口 22, 80, 443。"
fi

# 7. 启动Docker应用
log_info "启动应用容器..."
# 确保我们位于正确的目录
cd "$APP_DIR"
docker compose --env-file .env.prod up --build -d

# --- 部署完成 ---
log_info "🎉 部署完成! 🎉"
log_info "您的应用正在运行。请等待约一分钟让服务完全启动。"
log_info "然后通过浏览器访问: https://$DOMAIN"
log_info "您可以使用 'cd $APP_DIR && sudo docker-compose logs -f' 查看实时日志。" 